### ISSUE TITLE
Фидбэк по первой версии

### ISSUE THREAD

**Issue by kainwinterheart** [victoriaCat/Art_school#5]
Виктория, всё отлично, молодец, большое спасибо! Есть только пара мелких моментов, которые хотели бы попросить тебя поправить, если не затруднит. :)

1. Странный `undefined` в адресе картинки на странице списка мастер-классов; что-то потерялось?

<img width="626" alt="Art School 2020-03-23 22-10-36" src="https://user-images.githubusercontent.com/581366/77354419-ddda3600-6d53-11ea-9e3c-1a2b439fab4d.png">

2. Похоже, что ни у одной картинки (проверил картинки на странице списка мастер-классов и карусель внизу главной страницы, но думаю, что везде одно и то же) не указаны размеры, и везде грузятся оригинальные версии картинок, что очень плохо. Пришли список размеров картинок, которые нужны, я настрою под размеры ресайзер, и скажу, как поправить урлы.

<img width="576" alt="Art School 2020-03-23 22-16-11" src="https://user-images.githubusercontent.com/581366/77354568-1aa62d00-6d54-11ea-9583-0b7440eabacd.png">

3. 2019 год в подвале, хотя уже конец марта 2020. Надо сделать динамическую подстановку даты, и написать "2019 - текущая_дата".

<img width="700" alt="Art School 2020-03-23 22-14-22" src="https://user-images.githubusercontent.com/581366/77354924-aa4bdb80-6d54-11ea-997d-bfb68080951f.png">

4. Если посмотреть исходный код страницы, то видно, что почтовый адрес и телефон as-is зашиты в сам код. Так делать нельзя: спам-боты на раз-два собирают адреса и телефоны, и заваливают их мусором. Обычно такие вещи в коде страницы кодируются, а потом на лету расшифровываются при отрисовке страницы (например, посмотри на https://mpgu.pushkareva.art/exhibitions/ , увидь там адрес электронной почты в третьем абзаце, а потом загляни в исходный код страницы, и поищи там слово `beautify`).

5. Код Google Analytics и Яндекс.Метрики закомментирован: кажется, так не должно быть.

6. Шрифт сейчас загружается напрямую с Гугла, надо переложить в статические файлы в репозиторий, и брать его оттуда: это работает надёжней.

7. См. скриншот ниже.

<img width="1080" alt="Art School 2020-03-23 22-38-53" src="https://user-images.githubusercontent.com/581366/77356400-437bf180-6d57-11ea-8ffe-30d982cd923e.png">

8. Политика конфиденциальности, страница конкретного мастер-класса, и, вероятно, что-то ещё, что открывается в новой вкладке, открывается без шапки: это плохо, потому что мешает дальнейшей работе с сайтом. Надо либо добавить шапку, либо сделать это модальными окнами.

9. Несколько комментариев по дизайну, в том числе - проблемы на большом экране, а так же мелкие правки в текстах:

![photo_2020-03-24_03-07-21](https://user-images.githubusercontent.com/581366/77374773-a8960e00-6d7c-11ea-95be-a7e174ed2060.jpg)
![photo_2020-03-24_03-07-18](https://user-images.githubusercontent.com/581366/77374776-aaf86800-6d7c-11ea-9ca5-b7be1143d63d.jpg)
![photo_2020-03-24_03-07-14](https://user-images.githubusercontent.com/581366/77374778-ab90fe80-6d7c-11ea-8e2d-64805da7d073.jpg)
![photo_2020-03-24_03-07-10](https://user-images.githubusercontent.com/581366/77374779-ac299500-6d7c-11ea-87a3-b92eb8aa6e15.jpg)
![photo_2020-03-24_03-07-06](https://user-images.githubusercontent.com/581366/77374781-acc22b80-6d7c-11ea-88d3-6cce39fafb3c.jpg)
![photo_2020-03-24_03-07-01](https://user-images.githubusercontent.com/581366/77374783-ad5ac200-6d7c-11ea-8336-a913a8ee5a18.jpg)
![photo_2020-03-24_03-06-57](https://user-images.githubusercontent.com/581366/77374785-ad5ac200-6d7c-11ea-874b-cd4d2097092c.jpg)
![photo_2020-03-24_03-06-53](https://user-images.githubusercontent.com/581366/77374786-adf35880-6d7c-11ea-87b1-87c352c5101e.jpg)
![photo_2020-03-24_03-06-44](https://user-images.githubusercontent.com/581366/77374787-adf35880-6d7c-11ea-88fb-b4c814fb072d.jpg)

**Comment by victoriaCat** [comment]
Исправлено всё, кроме пункта 2.
